apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bgd-base
commonLabels:
  env: production
patches:
  - path: change-to-configmap.yaml
configMapGenerator:
  - name: color-config
    literals:
      - color.prod=GREEN
