apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: bgd
          env:
            - name: COLOR
              value: "green"
            - name: SOME_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: some-config
                  key: config.prod
            - name: DATE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: date-config
                  key: date
          resources:
            limits:
              cpu: 3000m
